from api.apis.carriers.fedex.soap_objects.common.party import Party

SUCCESSFUL_TRANSACTION = 1
RESEND_TRANSACTION = 2
TRANSACTION_FAIL = 3
NOTIFICATIONS = {
    "Success": SUCCESSFUL_TRANSACTION,
    "Note": SUCCESSFUL_TRANSACTION,
    "Warning": SUCCESSFUL_TRANSACTION,
    "Failure": RESEND_TRANSACTION,
    "ERROR": TRANSACTION_FAIL,
}

CARRIER_CODES = {"FDXC", "FDXE", "FDXG", "FXCC", "FXFR", "FXSP"}

DROPOFF_TYPE = "REGULAR_PICKUP"
PACKAGING_TYPE = "YOUR_PACKAGING"
POUNDS = "LB"
INCHES = "IN"
CENTIMETERS = "CM"
KILOGRAMS = "KG"

PHYSICAL_PACKAGING_TYPE = "OTHER"

MONETARY_CURRENCY = "CAD"
PAYMENT_TYPE = "SENDER"
BBE_PAYOR = Party(
    {
        "company_name": "BBE Expediting Ltd",
        "phone": "",
        "email": "",
        "address": "1759 35 Ave E",
        "city": "Edmonton International Airport",
        "province": "AB",
        "postal_code": "T9E0V6",
        "country": "CA",
    },
    is_payor=True,
).data

BROKER_TYPE = "BROKER_INCLUSIVE"
BROKER_SEL_TYPE = "BROKER_SELECT"
EXPORT_TYPE = "OTHER"
EXPORT_DESCRIPTION = "Sale"
EXPORT_RECIPIENT_TYPE = "COMPANY"
EXPORT_DOCUMENT_CONTENT = "NON_DOCUMENTS"
PURPOSE_OF_SHIPMENT = "BUSINESS"
TERMS_OF_SALE = "Delivered Duties Unpaid"
COMMODITY_QUANTITY_UNITS = "Each"

FUTURE_PICKUP_REQUEST = "FUTURE_DAY"
SAME_DAY_PICKUP_REQUEST = "SAME_DAY"
PICKUP_REQUEST_SOURCE = "AUTOMATION"

LABEL_FORMAT_TYPE = "OPERATIONAL_LABEL"
SHIPPING_LABEL_FORMAT_TYPE = "COMMON2D"
LABEL_IMAGE_TYPE = "PDF"
LABEL_STOCK_TYPE = "STOCK_4X6"
LABEL_PRINTING_ORIENTATION = "BOTTOM_EDGE_OF_TEXT_FIRST"
LABEL_ROTATION = "NONE"
LABEL_ORDER = "SHIPPING_LABEL_FIRST"

ENGLISH = "EN"
CANADA_ENGLISH = "ca"

COMMERCIAL_INVOICE_TYPE = "COMMERCIAL_INVOICE"

RATE_REQUEST_TYPE = ["PREFERRED"]
ESTIMATE_DUTIES_TAXES = "ALL"

TRANSIT_TIME = {
    "ONE_DAY": 1,
    "TWO_DAYS": 2,
    "THREE_DAYS": 3,
    "FOUR_DAYS": 4,
    "FIVE_DAYS": 5,
    "SIX_DAYS": 6,
    "SEVEN_DAYS": 7,
    "EIGHT_DAYS": 8,
    "NINE_DAYS": 9,
    "TEN_DAYS": 10,
    "ELEVEN_DAYS": 11,
    "TWELVE_DAYS": 12,
    "THIRTEEN_DAYS": 13,
    "FOURTEEN_DAYS": 14,
    "FIFTEEN_DAYS": 15,
    "SIXTEEN_DAYS": 16,
    "SEVENTEEN_DAYS": 17,
    "EIGHTEEN_DAYS": 18,
    "NINETEEN_DAYS": 19,
    "TWENTY_DAYS": 20,
}

SERVICES_CA_DICT = {
    "06": "FIRST_OVERNIGHT",
    "01": "PRIORITY_OVERNIGHT",
    "05": "STANDARD_OVERNIGHT",
    "03": "FEDEX_2_DAY",
    "20": "FEDEX_EXPRESS_SAVER",
    "92": "FEDEX_GROUND",
}

SERVICES_INT_DICT = {
    "06": "INTERNATIONAL_FIRST",
    "01": "INTERNATIONAL_PRIORITY",
    "03": "INTERNATIONAL_ECONOMY",
    "04": "INTERNATIONAL_ECONOMY",
    "92": "FEDEX_GROUND",
    "70": "INTERNATIONAL_PRIORITY_FREIGHT",
}

EXPRESS_SERVICES = (
    "EUROPE_FIRST_INTERNATIONAL_PRIORITY",
    "FEDEX_1_DAY_FREIGHT",
    "FEDEX_2_DAY",
    "FEDEX_2_DAY_AM",
    "FEDEX_2_DAY_FREIGHT",
    "FEDEX_3_DAY_FREIGHT",
    "FEDEX_CARGO_AIRPORT_TO_AIRPORT",
    "FEDEX_CARGO_FREIGHT_FORWARDING",
    "FEDEX_CARGO_INTERNATIONAL_EXPRESS_FREIGHT",
    "FEDEX_CARGO_INTERNATIONAL_PREMIUM",
    "FEDEX_CARGO_MAIL",
    "FEDEX_CARGO_REGISTERED_MAIL",
    "FEDEX_CARGO_SURFACE_MAIL",
    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE",
    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE",
    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK",
    "FEDEX_CUSTOM_CRITICAL_CHARTER_AIR",
    "FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT",
    "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE",
    "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE",
    "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR",
    "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR",
    "FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES",
    "FEDEX_DISTANCE_DEFERRED",
    "FEDEX_EXPRESS_SAVER",
    "FEDEX_FIRST_FREIGHT",
    "FEDEX_FREIGHT_ECONOMY",
    "FEDEX_FREIGHT_PRIORITY",
    "FEDEX_INTERNATIONAL_PRIORITY_PLUS",
    "FEDEX_NEXT_DAY_AFTERNOON",
    "FEDEX_NEXT_DAY_EARLY_MORNING",
    "FEDEX_NEXT_DAY_END_OF_DAY",
    "FEDEX_NEXT_DAY_FREIGHT",
    "FEDEX_NEXT_DAY_MID_MORNING",
    "FIRST_OVERNIGHT",
    "INTERNATIONAL_DISTRIBUTION_FREIGHT",
    "INTERNATIONAL_ECONOMY",
    "INTERNATIONAL_ECONOMY_DISTRIBUTION",
    "INTERNATIONAL_ECONOMY_FREIGHT",
    "INTERNATIONAL_FIRST",
    "INTERNATIONAL_PRIORITY",
    "INTERNATIONAL_PRIORITY_DISTRIBUTION",
    "INTERNATIONAL_PRIORITY_EXPRESS",
    "INTERNATIONAL_PRIORITY_FREIGHT",
    "PRIORITY_OVERNIGHT",
    "SAME_DAY",
    "SAME_DAY_CITY",
    "SAME_DAY_METRO_AFTERNOON",
    "SAME_DAY_METRO_MORNING",
    "SAME_DAY_METRO_RUSH",
    "SMART_POST",
    "STANDARD_OVERNIGHT",
    "TRANSBORDER_DISTRIBUTION_CONSOLIDATION",
)

GROUND_SERVICES = (
    "GROUND_HOME_DELIVERY",
    "INTERNATIONAL_GROUND",
    "FEDEX_GROUND",
)
