
BBE = 1
KENCAR = 17
KENCARINC = 18

# In House
UBBE_LTL = 900
UBBE_COURIER = 901
UBBE_AIR = 902
UBBE_INTERLINE = 903
UBBE_ML = 904

# Air
CAN_NORTH = 708
AIR_NORTH = 737
WESTJET = 747
CALM_AIR = 616

AIR_TINDI = 301
NORTH_WRIGHT = 302
AIR_NUNAVUT = 303
KEEWATIN_AIR = 304
PANORAMA_AIR = 305
PERIMETER_AIR = 306
CARGO_JET = 307
BUFFALO_AIRWAYS = 308
AIR_INUIT = 309

# Courier
FEDEX = 2
PUROLATOR = 11
ACTION_EXPRESS = 601
CAN_POST = 20
UPS = 8
DHL = 7
GILL_COURIER = 95
CROSS_BORDER = 90
SAMEDAY = 123
LOOMIS = 30
WINNIE = 719
TFORCE = 720
CEVA = 721
rx_express = 722
quickx = 723
APPLE_EXPRESS = 724
INTERCUBE = 725
PACER = 726
BUFFALO_COURIER = 767
AEROXPRESS = 728
A1_DELIVERY = 729
LES_MESSAGER = 730

# LTL
PUROLATOR_FREIGHT = 734

MANITOULIN = 535
KINGSWAY = 646
LANDTRAN = 650
CAN_FREIGHT = 127
YRC = 523
OVERLAND_WEST = 670
COMOX_PACIFIC = 71
TST = 129
TST_US = 130
DAY_N_ROSS = 122
GRADEWINE = 70
MUSTANG = 502
VAN_KAM = 503
PACIFIC_NORTHWEST = 504
NORTHWIND = 505
GRIMSHAW = 506
HIWAY = 507
LEINSTER = 508
DETONCHO = 509
ROSNEAU = 510
BANDSTRA = 511
ABF_FREIGHT = 512
JJ_TRANSPORT = 513

# Sealift
NEAS = 40
NSSI = 41
MTS = 42
FATHOM = 43

# FTL
ANDY = 50
MORNEAU = 51
TOLOGIS = 52
CATGLOBAL = 53
ROBERT = 54
GRADEWINE_FTL = 55
CHALLENGER = 56
MANITOULIN_FTL = 57
OVERLAND_WEST_FTL = 58
CONTINENTAL = 59

# Charters
CHARTER_ONE = 950
CHARTER_TWO = 951
CHARTER_THREE = 952
CHARTER_FOUR = 953
CHARTER_FIVE = 954

# FedEx ground service
FEDEX_GROUND = 92
FEDEX_REMOVED = ("70", "86")

SKYLINE_CARRIERS = (CAN_NORTH,)
TWO_SHIP_CARRIERS = (
    UPS,
    DHL,
    PUROLATOR_FREIGHT,
)
TWO_SHIP_API_CARRIERS = (
    UPS,
    DHL,
    PUROLATOR_FREIGHT,
)
RATE_SHEET_CARRIERS = (
    KINGSWAY,
    LANDTRAN,
    # TST,
    # TST_US,
    # CAN_FREIGHT,
    VAN_KAM,
    OVERLAND_WEST,
    COMOX_PACIFIC,
    GILL_COURIER,
    CROSS_BORDER,
    CEVA,
    TFORCE,
    WINNIE,
    MUSTANG,
    KENCAR,
    ANDY,
    MORNEAU,
    TOLOGIS,
    CATGLOBAL,
    ROBERT,
    GRADEWINE,
    GRADEWINE_FTL,
    CHALLENGER,
    MANITOULIN_FTL,
    OVERLAND_WEST_FTL,
    PACIFIC_NORTHWEST,
    NORTHWIND,
    rx_express,
    quickx,
    GRIMSHAW,
    # DAY_N_ROSS,
    UBBE_LTL,
    UBBE_COURIER,
    HIWAY,
    BUFFALO_COURIER,
    BUFFALO_AIRWAYS,
    APPLE_EXPRESS,
    AIR_NORTH,
    INTERCUBE,
    PACER,
    AIR_TINDI,
    NORTH_WRIGHT,
    AIR_NUNAVUT,
    KEEWATIN_AIR,
    CHARTER_ONE,
    CHARTER_TWO,
    CHARTER_THREE,
    CHARTER_FOUR,
    CHARTER_FIVE,
    PANORAMA_AIR,
    KENCARINC,
    LEINSTER,
    PERIMETER_AIR,
    # CARGO_JET,
    DETONCHO,
    WESTJET,
    FATHOM,
    ROSNEAU,
    AEROXPRESS,
    CONTINENTAL,
    BANDSTRA,
    A1_DELIVERY,
    AIR_INUIT,
    LES_MESSAGER,
    JJ_TRANSPORT
)

COURIERS_CARRIERS = {
    FEDEX,
    PUROLATOR,
    DHL,
    CAN_POST,
    ACTION_EXPRESS,
    CEVA,
    TFORCE,
    WINNIE,
    GILL_COURIER,
    CROSS_BORDER,
    rx_express,
    quickx,
    UPS,
    APPLE_EXPRESS,
    INTERCUBE,
    PACER,
    KENCARINC,
    BUFFALO_COURIER,
    AEROXPRESS,
    SAMEDAY,
    LOOMIS,
    A1_DELIVERY,
    LES_MESSAGER
}

LTL_CARRIERS = (
    MANITOULIN,
    KINGSWAY,
    LANDTRAN,
    TST,
    TST_US,
    CAN_FREIGHT,
    VAN_KAM,
    OVERLAND_WEST,
    COMOX_PACIFIC,
    BBE,
    MUSTANG,
    GRADEWINE,
    PACIFIC_NORTHWEST,
    NORTHWIND,
    GRIMSHAW,
    DAY_N_ROSS,
    PUROLATOR_FREIGHT,
    UBBE_LTL,
    HIWAY,
    DETONCHO,
    ROSNEAU,
    YRC,
    UBBE_ML,
    UBBE_INTERLINE,
    BANDSTRA
)

FTL_CARRIERS = (
    KENCAR,
    ANDY,
    MORNEAU,
    TOLOGIS,
    CATGLOBAL,
    ROBERT,
    GRADEWINE_FTL,
    CHALLENGER,
    MANITOULIN_FTL,
    OVERLAND_WEST_FTL,
    CONTINENTAL,
    JJ_TRANSPORT
)

SEALIFT_CARRIERS = (
    NEAS,
    NSSI,
    MTS,
    FATHOM
)

AIR_CARRIERS = (
    CAN_NORTH,
    WESTJET,
    AIR_NORTH,
    CALM_AIR,
    AIR_TINDI,
    NORTH_WRIGHT,
    AIR_NUNAVUT,
    KEEWATIN_AIR,
    PANORAMA_AIR,
    PERIMETER_AIR,
    CARGO_JET,
    BUFFALO_AIRWAYS,
    AIR_INUIT
)
